//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VodovodEntities : DbContext
    {
        public VodovodEntities()
            : base("name=VodovodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEO_OPREME> DEO_OPREME { get; set; }
        public virtual DbSet<EKIPA> EKIPAs { get; set; }
        public virtual DbSet<KORISNIK> KORISNIKs { get; set; }
        public virtual DbSet<KVAR> KVARs { get; set; }
        public virtual DbSet<LOKACIJA> LOKACIJAs { get; set; }
        public virtual DbSet<MAGACIN> MAGACINs { get; set; }
        public virtual DbSet<NADLEZNI> NADLEZNIs { get; set; }
        public virtual DbSet<NALAZI_SE_NA> NALAZI_SE_NA { get; set; }
        public virtual DbSet<NALAZI_U> NALAZI_U { get; set; }
        public virtual DbSet<PRIJAVLJUJE> PRIJAVLJUJEs { get; set; }
        public virtual DbSet<PRIMA> PRIMAs { get; set; }
        public virtual DbSet<RACUN> RACUNs { get; set; }
        public virtual DbSet<RADNI_NALOG> RADNI_NALOG { get; set; }
        public virtual DbSet<RADNIIK> RADNIIKs { get; set; }
        public virtual DbSet<VODOVODNA_MREZA> VODOVODNA_MREZA { get; set; }
        public virtual DbSet<ZAPOSLENI> ZAPOSLENIs { get; set; }
    }
}
