//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EKIPA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EKIPA()
        {
            this.NALAZI_U = new HashSet<NALAZI_U>();
            this.RADNIIKs = new HashSet<RADNIIK>();
        }
    
        public string ID_EK { get; set; }
        public byte BR_RAD { get; set; }
        public string RADNI_NALOG_ID_RADNAL { get; set; }
        public string RADNI_NALOG_PRIMA_JMBG_ZAP { get; set; }
        public string RADNI_NALOG_PRIMA_JMBG_KOR { get; set; }
        public string RADNI_NALOG_PRIMA_ID_KVAR { get; set; }
    
        public virtual RADNI_NALOG RADNI_NALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NALAZI_U> NALAZI_U { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNIIK> RADNIIKs { get; set; }
    }
}
