//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOKACIJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOKACIJA()
        {
            this.NALAZI_SE_NA = new HashSet<NALAZI_SE_NA>();
        }
    
        public string SIF_LOK { get; set; }
        public string ULICA { get; set; }
        public string BROJ { get; set; }
        public string GRAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NALAZI_SE_NA> NALAZI_SE_NA { get; set; }
    }
}
