//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NALAZI_U
    {
        public string MAGACIN_ID_MAG { get; set; }
        public byte DEO_OPREME_ID_TIP { get; set; }
        public string ID_DEO { get; set; }
        public string EKIPA_ID_EK { get; set; }
    
        public virtual DEO_OPREME DEO_OPREME { get; set; }
        public virtual EKIPA EKIPA { get; set; }
        public virtual MAGACIN MAGACIN { get; set; }
    }
}
