//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NALAZI_SE_NA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NALAZI_SE_NA()
        {
            this.PRIJAVLJUJEs = new HashSet<PRIJAVLJUJE>();
        }
    
        public string ID_DEO_LOK { get; set; }
        public float DUBINA { get; set; }
        public string LOKACIJA_SIF_LOK { get; set; }
        public byte DEO_OPREME_ID_TIP { get; set; }
    
        public virtual DEO_OPREME DEO_OPREME { get; set; }
        public virtual LOKACIJA LOKACIJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIJAVLJUJE> PRIJAVLJUJEs { get; set; }
    }
}
