//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NALAZI_U
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NALAZI_U()
        {
            this.EKIPAs = new HashSet<EKIPA>();
        }
    
        public byte KOLICINA { get; set; }
        public string MAGACIN_ID_MAG { get; set; }
        public byte DEO_OPREME_ID_TIP { get; set; }
        public string ID_DEO { get; set; }
    
        public virtual DEO_OPREME DEO_OPREME { get; set; }
        public virtual MAGACIN MAGACIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EKIPA> EKIPAs { get; set; }
    }
}
