//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIJAVLJUJE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIJAVLJUJE()
        {
            this.PRIMAs = new HashSet<PRIMA>();
        }
    
        public string KORISNIK_JMBG_KOR { get; set; }
        public string KVAR_ID_KVAR { get; set; }
        public string NALAZI_SE_NA_ID_DEO_LOK { get; set; }
        public string NALAZI_SE_NA_SIF_LOK { get; set; }
        public byte NALAZI_SE_NA_ID_TIP { get; set; }
    
        public virtual KORISNIK KORISNIK { get; set; }
        public virtual KVAR KVAR { get; set; }
        public virtual NALAZI_SE_NA NALAZI_SE_NA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRIMA> PRIMAs { get; set; }
    }
}
