//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRIMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRIMA()
        {
            this.RACUNs = new HashSet<RACUN>();
            this.RADNI_NALOG = new HashSet<RADNI_NALOG>();
        }
    
        public string NADLEZNI_JMBG_ZAP { get; set; }
        public string PRIJAVLJUJE_KORISNIK_JMBG_KOR { get; set; }
        public string PRIJAVLJUJE_KVAR_ID_KVAR { get; set; }
    
        public virtual NADLEZNI NADLEZNI { get; set; }
        public virtual PRIJAVLJUJE PRIJAVLJUJE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RACUN> RACUNs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADNI_NALOG> RADNI_NALOG { get; set; }
    }
}
