//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACUN
    {
        public string ID_RAC { get; set; }
        public decimal CENA { get; set; }
        public string PRIMA_JMBG_ZAP { get; set; }
        public string PRIMA_JMBG_KOR { get; set; }
        public string PRIMA_ID_KVAR { get; set; }
    
        public virtual PRIMA PRIMA { get; set; }
    }
}
