//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADNIIK
    {
        public string JMBG_ZAP { get; set; }
        public string EKIPA_ID_EK { get; set; }
    
        public virtual EKIPA EKIPA { get; set; }
        public virtual ZAPOSLENI ZAPOSLENI { get; set; }
    }
}
