CREATE TABLE [dbo].[EKIPA]
(
	ID_EK                      VARCHAR (10) NOT NULL ,
    BR_RAD                     TINYINT NOT NULL ,
    RADNI_NALOG_ID_RADNAL      VARCHAR (10) ,
    RADNI_NALOG_PRIMA_JMBG_ZAP CHAR (13) ,
    RADNI_NALOG_PRIMA_JMBG_KOR CHAR (13) ,
    RADNI_NALOG_PRIMA_ID_KVAR  VARCHAR (10)
)
