CREATE TABLE [dbo].[NALAZI_U]
(
	KOLICINA          TINYINT NOT NULL ,
    MAGACIN_ID_MAG    VARCHAR (10) NOT NULL ,
    DEO_OPREME_ID_TIP TINYINT NOT NULL ,
    ID_DEO            VARCHAR (10) NOT NULL
)
