CREATE TABLE [dbo].[PRIJAVLJUJE]
(
	KORISNIK_JMBG_KOR       CHAR (13) NOT NULL ,
    KVAR_ID_KVAR            VARCHAR (10) NOT NULL ,
    NALAZI_SE_NA_ID_DEO_LOK VARCHAR (10) NOT NULL ,
    NALAZI_SE_NA_SIF_LOK    VARCHAR (10) NOT NULL ,
    NALAZI_SE_NA_ID_TIP     TINYINT NOT NULL
)
