CREATE TABLE [dbo].[RACUN]
(
	ID_RAC VARCHAR (10) NOT NULL ,
    CENA MONEY NOT NULL ,
    PRIMA_JMBG_ZAP CHAR (13) NOT NULL ,
    PRIMA_JMBG_KOR CHAR (13) NOT NULL ,
    PRIMA_ID_KVAR  VARCHAR (10) NOT NULL
)
