ALTER TABLE EKIPA
ADD CONSTRAINT EKIPA_RADNI_NALOG_FK 
	FOREIGN KEY
		(RADNI_NALOG_ID_RADNAL,
		RADNI_NALOG_PRIMA_JMBG_ZAP,
		RADNI_NALOG_PRIMA_JMBG_KOR,
		RADNI_NALOG_PRIMA_ID_KVAR)
	REFERENCES RADNI_NALOG
		(ID_RADNAL ,
		PRIMA_JMBG_ZAP ,
		PRIMA_JMBG_KOR ,
		PRIMA_ID_KVAR)