ALTER TABLE PRIJAVLJUJE
ADD CONSTRAINT PRIJAVLJUJE_NALAZI_SE_NA_FK FOREIGN KEY
(
NALAZI_SE_NA_ID_DEO_LOK,
NALAZI_SE_NA_SIF_LOK,
NALAZI_SE_NA_ID_TIP
)
REFERENCES NALAZI_SE_NA
(
ID_DEO_LOK ,
LOKACIJA_SIF_LOK ,
DEO_OPREME_ID_TIP
)