ALTER TABLE RADNI_NALOG
ADD CONSTRAINT RADNI_NALOG_PRIMA_FK FOREIGN KEY
(
PRIMA_JMBG_ZAP,
PRIMA_JMBG_KOR,
PRIMA_ID_KVAR
)
REFERENCES PRIMA
(
NADLEZNI_JMBG_ZAP ,
PRIJAVLJUJE_KORISNIK_JMBG_KOR ,
PRIJAVLJUJE_KVAR_ID_KVAR
)